export enum ErrorMessage {
  required = "Campo obrigatório",
  equals = "Escolha o valor correto",
  min = "Digite o valor maior",
  max = "Digite o valor menor",
  notEquals = "Senhas não conferem",
  invalidRG = "RG inválido",
  invalidCPF = "CPF inválido",
  invalidPrice = "Preço inválido",
  invalidDate = "Data inválida",
  invalidMinDate = "Digite uma data posterior",
  invalidEmail = "Email inválido",
  invalidPassword = "Senhas inválida",
  invalidLength = "Digite ao menos 7 digitos",
  invalidContact = "Digite um contato válido",
}
